# node-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: file-sink-metrics
  namespace: default
  labels:
    app: file-sink
spec:
  selector:
    app: file-sink
  ports:
    - name: metrics
      port: 8123
      targetPort: 8123
      protocol: TCP
  type: ClusterIP