# node-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-server-metrics
  namespace: default
  labels:
    app: node-server
spec:
  selector:
    app: node-server
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP