# otel-collector-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'node-server'
              kubernetes_sd_configs:
                - role: endpoints
                  namespaces:
                    names: ["default"]
              relabel_configs:
                - source_labels: [__meta_kubernetes_service_label_app]
                  action: keep
                  regex: node-server
                - source_labels: [__meta_kubernetes_endpoint_port_name]
                  action: keep
                  regex: metrics
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: kubernetes_namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: kubernetes_pod_name
                - source_labels: [__address__]
                  regex: (.+):(\d+)
                  target_label: instance
                  replacement: ${1}:${2}

    processors:
      batch:

    exporters:
      # Експортуємо метрики до Prometheus Remote Write
      prometheusremotewrite:
        endpoint: "http://prometheus-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
      logging:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [prometheusremotewrite, logging]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging] 