apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: file-sink-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: file-sink
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s