{
 "title": "PostgeSQL metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Exporter Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"postgres-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"mydatabase\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_locks_count{mode=\"ExclusiveLock\", granted=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"mydatabase\"} / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Duration - P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(pg_stat_activity_query_time_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}