{
 "title": "node-server-telemetry",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cpu Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodejs External Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Lag P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p50_seconds\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Active NodeJs Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "nodejs_active_resources_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}