apiVersion: camel.apache.org/v1  # Specifies the API version of Camel K.
kind: Pipe  # This resource type is a Pipe, a custom Camel K resource for defining integration flows.
metadata:
  name: pipe  # The name of the Pipe, which identifies this particular integration flow.
  annotations:
    trait.camel.apache.org/mount.configs: "secret:slack-credentials"  # An annotation that specifies the secret to mount for the Pipe.
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: timer-source
    properties:
      message: '{"reviewText": "This is a test"}'
      period: 10000  # every 3 seconds
  sink:  # Defines the destination for events processed by this Pipe.
    ref:
      kind: Kamelet  # Specifies that the sink is a Kamelet, a Camel K component for connecting to external services.
      apiVersion: camel.apache.org/v1  # The API version for Kamelet.
      name: unstable-slack-sink  # The name of the Kamelet to use as the sink, in this case, a predefined "slack-sink" Kamelet.
    properties:
      channel: ${slack.channel}  # The channel to post messages to, specified in the secret.
      webhookUrl: ${slack.webhook.url} # The webhook URL to use for posting messages, specified in the secret.