apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: unstable-slack-sink
spec:
  definition:
    title: "Unstable Slack Sink"
    required:
      - webhookUrl
    properties:
      webhookUrl:
        type: string
        description: "Slack webhook URL"
      channel:
        type: string
        description: "Slack channel"
  template:
    from:
      uri: "kamelet:source"
      steps:
        - choice:
            when:
              - expression:
                  simple: "${random(1,5)} == 1"
                steps:
                  - log:
                      message: "Simulated failure"
                  - throwException:
                      exceptionType: "java.lang.RuntimeException"
                      message: "Random simulated Slack failure"
            otherwise:
              steps:
                - set-header:
                    name: Content-Type
                    constant: application/json
                - marshal:
                    json:
                      library: Jackson
                - toD: "https://{{webhookUrl}}"
