# postgres-exporter-creds-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-creds
  namespace: default
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://myuser:mypassword@postgresql:5432/mydatabase?sslmode=disable"
